# Dùng JRE 17 phiên bản Alpine (nhẹ)
FROM eclipse-temurin:17-jre-alpine

# Tạo thư mục làm việc
WORKDIR /app

# Copy file JAR (match tên đúng)
COPY target/service-registry*.jar app.jar

# Khởi chạy ứng dụng
ENTRYPOINT ["java", "-jar", "app.jar"]
